"""add_detection_tables

Revision ID: 2766f85eb50d
Revises: ee6daff0d589
Create Date: 2026-09-16 14:35:05.432100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2766f85eb50d'
down_revision: Union[str, Sequence[str], None] = 'ee6daff0d589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_detection_rules_enabled', 'detection_rules', ['enabled'], unique=False)
    op.create_index('ix_detection_rules_name', 'detection_rules', ['name'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('first_event_id', sa.Integer(), nullable=False),
    sa.Column('last_event_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['detection_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_detected_at', 'alerts', ['detected_at'], unique=False)
    op.create_index('ix_alerts_first_event_id', 'alerts', ['first_event_id'], unique=False)
    op.create_index('ix_alerts_last_event_id', 'alerts', ['last_event_id'], unique=False)
    op.create_index('ix_alerts_rule_id', 'alerts', ['rule_id'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('alert_events',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'event_id', name='pk_alert_event')
    )
    op.create_index('ix_alert_events_event_id', 'alert_events', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_event_id', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_rule_id', table_name='alerts')
    op.drop_index('ix_alerts_last_event_id', table_name='alerts')
    op.drop_index('ix_alerts_first_event_id', table_name='alerts')
    op.drop_index('ix_alerts_detected_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_detection_rules_name', table_name='detection_rules')
    op.drop_index('ix_detection_rules_enabled', table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
