"""add_incident_correlation

Revision ID: 88d0e2ecf30b
Revises: 2766f85eb50d
Create Date: 2026-09-16 14:56:03.386118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d0e2ecf30b'
down_revision: Union[str, Sequence[str], None] = '2766f85eb50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('correlation_key', sa.String(length=256), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_correlation_key', 'incidents', ['correlation_key'], unique=False)
    op.create_index('ix_incidents_last_seen_at', 'incidents', ['last_seen_at'], unique=False)
    op.create_index('ix_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_status', 'incidents', ['status'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'alert_id', name='pk_incident_alert'),
    sa.UniqueConstraint('alert_id', name='uq_incident_alert_alert_id')
    )
    op.create_index('ix_incident_alerts_alert_id', 'incident_alerts', ['alert_id'], unique=False)
    op.create_index('ix_incident_alerts_incident_id', 'incident_alerts', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incident_alerts_incident_id', table_name='incident_alerts')
    op.drop_index('ix_incident_alerts_alert_id', table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_index('ix_incidents_status', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_last_seen_at', table_name='incidents')
    op.drop_index('ix_incidents_correlation_key', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
