"""baseline_m1_m2

Revision ID: ee6daff0d589
Revises: 
Create Date: 2026-09-16 14:34:02.317978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6daff0d589'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_log', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_host', 'events', ['host'], unique=False)
    op.create_index('ix_events_level', 'events', ['level'], unique=False)
    op.create_index('ix_events_service', 'events', ['service'], unique=False)
    op.create_index('ix_events_source', 'events', ['source'], unique=False)
    op.create_index('ix_events_timestamp', 'events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_timestamp', table_name='events')
    op.drop_index('ix_events_source', table_name='events')
    op.drop_index('ix_events_service', table_name='events')
    op.drop_index('ix_events_level', table_name='events')
    op.drop_index('ix_events_host', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
